server:
  port: 80
# 服务别名
spring:
  application:
    name: cloud-consumer-order
  # consul配置
  cloud:
    consul:
      host: mrmao.life
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true